### ISSUE TITLE
How to use NVTX.jl with CUDA-aware MPI?

### ISSUE THREAD

**Issue by ZenanH** [simonbyrne/NVTX.jl#45]
Hi, I used command `nsys profile --trace=nvtx,mpi --mpi-impl=openmpi mpirun -n 2 julia -O3 --color=yes t10.jl` to run the code:

```julia
# t10.jl
function main()
    MPI.Init()
    comm = MPI.COMM_WORLD
    rank = MPI.Comm_rank(comm)
    n = 10000000

    CUDA.device!(rank)

    if rank == 0
        sendmsg = CUDA.rand(n, 30)
    elseif rank == 1
        recvmsg = CUDA.zeros(n, 30)
    end

    CUDA.synchronize()
    MPI.Barrier(comm)
    
    if rank == 0
        NVTX.@range "send data" begin
            MPI.Isend(sendmsg, comm; dest=1, tag=1)
        end
    elseif rank == 1
        NVTX.@range "receive data" begin 
            rreq = MPI.Irecv!(recvmsg, comm; source=0, tag=1)
            MPI.Wait(rreq)
            recvmsg .+= recvmsg .^ 2
        end
    end

    CUDA.synchronize()
    MPI.Barrier(comm)
end

main()
```

But I cannot see GPU utilization in Nsight-system:
![image](https://github.com/JuliaGPU/NVTX.jl/assets/19581645/d3e2ca13-b3fe-4865-8cfa-2399e4f0dd6f)

Did I do something wrong?😅

**Comment by simonbyrne** [comment]
You may need to trace `cuda` as well, i.e. `--trace=nvtx,mpi,cuda`?

If that doesn't work, try using the profiler inside mpirun: I had better results with that.

**Comment by simonbyrne** [comment]
If I was to hazard a guess:
- the gap at the start is compilation.
- the gap at the end is the GPU finishing work that was launched.
