### ISSUE TITLE
Convenience macros (as in CUDA.jl)

### ISSUE THREAD

**Issue by carstenbauer** [simonbyrne/NVTX.jl#5]
In CUDA.jl, there are `NVTX.@range "some section" expr` and `NVTX.@mark "reached some point"` (see [here](https://cuda.juliagpu.org/stable/development/profiling/#Source-code-annotations)). Would be great to have something similar here as well.

CUDA.jl source code link: https://github.com/JuliaGPU/CUDA.jl/blob/v3.12.0/lib/nvtx/highlevel.jl#L70

**Comment by simonbyrne** [comment]
agreed!

**Comment by carstenbauer** [comment]
Thanks for implementing this! Will try it out soon.
